### ISSUE TITLE
Request to add ability to delete a version via API without having to delete/reupload the whole title

### ISSUE THREAD

**Issue by georgecm12** [brysontyrrell/CommunityPatch#5]
It'd be nice to be able to delete a particular version of a title via the API. Case in point, a developer pulls back a release after discovering a problem.

(Or, you know... someone might inadvertently add a version without reviewing what is being uploaded, and then they notice that they made an error in the JSON. Not like that would ever happen, you know... ahem... ;))

**Comment by brysontyrrell** [comment]
This is now implemented in Beta 2.
